server:
  port: 8099
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 18

spring:
  application:
    # 用于指定这个微服务名称，也就是在注册中心显示的名称，其他微服务同个这个名称调用服务
    name: spring-cloud-admin-server
    #添加security 后设置账号密码
#    profiles: secure
#    security:
#      user:
#        name: admin
#        password: admin
# log level
logging.level:
  root: WARN
  org.springframework: DEBUG
  org.apache.coyote.http11.Http11InputBuffer: DEBUG
  sample.mybatis.mapper: DEBUG
  org.apache.ibatis: DEBUG
#服务注册发现
eureka:
  instance:
#    metadata-map:
#      user.name: admin
#      user.password: admin
    appname: cloud-admin-server # name
    prefer-ip-address: true # ip show

  client: #客户端注册进eureka服务列表内
    register-with-eureka: true #
    fetch-registry: true #是否从eureka上获取注册信息
    service-url:
      #
      defaultZone: http://localhost:9000/eureka/ #这个地址就是在 Eureka 服务端的 application.yml 上暴露出的服务地址（这行后面加注释，可能会报错）

