server:
  port: 9000
  #address: 192.168.0.102
spring:
  application:
    # 用于指定这个微服务名称，也就是在注册中心显示的名称，其他微服务同个这个名称调用服务
    name: eureka-service

#eureka cfg
eureka:
  instance:
    hostname: localhost
    #hostname: 192.168.0.100
    appname: yichuan-eureka-server # name
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

    Connection: Keep-Alive
    prefer-ip-address: true # ip show
    #app-group-name: cloud-server
  server:
    enable-self-preservation: false #设为false，关闭自我保护
    eviction-interval-timer-in-ms: 5000 # 清理间隔（单位毫秒，默认是60*1000）

  client: #not a client,don't register with yourself
    registerWithEureka: false # false表示自己不需要向注册中心注册自己
    fetchRegistry: false # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka  #设置与Eureka Server交行的地址查询服务和注册服务

security:
  basic:
    #关闭安全验证
    enabled: false

# info信息会显示到SBA的server端，这里取的是maven中的数据
info:
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@